### ISSUE TITLE
Memwatch failed to build with node v0.11.16

### ISSUE THREAD

**Issue by jeremieca** [lloyd/node-memwatch#59]
Hello,

All the problem is describe in title !

Thanks !

```
  > memwatch@0.2.2 install        /Volumes/DataHD/.../project/node_modules/memwatch
 > node-gyp rebuild

 child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/memwatch/src/heapdiff.o
  In file included from ../src/heapdiff.cc:5:
 ../src/heapdiff.hh:14:35: error: expected class name
     class HeapDiff : public node::ObjectWrap
                              ^
 ../src/heapdiff.hh:19:49: error: no type named 'Arguments' in namespace 'v8'; did you mean      'v8::internal::Arguments'?
         static v8::Handle<v8::Value> New( const v8::Arguments& args );
                                                 ^~~~~~~~~~~~~
                                            v8::internal::Arguments
       /Users/jeremieca/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments'      declared here
 class Arguments;
          ^
 In file included from ../src/heapdiff.cc:5:
  ../src/heapdiff.hh:20:49: error: no type named 'Arguments' in namespace 'v8'; did you mean      'v8::internal::Arguments'?
         static v8::Handle<v8::Value> End( const v8::Arguments& args );
                                                 ^~~~~~~~~~~~~
                                            v8::internal::Arguments
 /Users/jeremieca/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
 class Arguments;
         ^
 ../src/heapdiff.cc:30:34: error: member initializer 'ObjectWrap' does not name a non-static data member or base class
  heapdiff::HeapDiff::HeapDiff() : ObjectWrap(), before(NULL), after(NULL),
                                   ^~~~~~~~~~~~
 ../src/heapdiff.cc:51:21: error: calling a protected constructor of class 'v8::HandleScope'
v8::HandleScope scope;
                       ^
```

**Comment by panta82** [comment]
Similar output for the just released node 0.12.0. Is this project still being worked on?

**Comment by jeremieca** [comment]
If project is dead, do you know any project able to replace memwatch ?

**Comment by majimboo** [comment]
This can be fixed by fixing some variables in the source but 2013 was the last commit and thats a long time ago so I doubt this will still be officially updated. But there are a lot of new similar modules, one is found [here](http://strongloop.com/strongblog/node-js-performance-tip-of-the-week-memory-leak-diagnosis/).

**Comment by jeremieca** [comment]
Thanks. But this project does not totally replace memwatch. The good thing with memwatch is the detection of memory leak in realtime. In dev mode, when my app is running, memwatch often check the heap and inform me if it grows 5 consecutive times after GC.

Heapdump module seems to just offer snapshot and inspection. No background task for realtime control. 

Do you now a module doing that (in the "lot of similar modules"). I don't find this. Thanks.

**Comment by panta82** [comment]
At this point, I'm just moving away from this sort of monitoring. I can detect memory leaks by watching process memory usage from the system. And then I can debug using heapdump and node-inspector.

**Comment by jeremieca** [comment]
Ok thanks. I'm sad...

**Comment by saschakiefer** [comment]
@majimboo is there a documentation about what to fix? I try to install BipIO on my mac. This fails, cause memwatch won't be installed...

**Comment by majimboo** [comment]
@saschakiefer , @jeremieca , @panta82 someone already fixed it. I guess its on the pull requests. https://github.com/marcominetti/node-memwatch

**Comment by francisdb** [comment]
pull request here https://github.com/lloyd/node-memwatch/pull/60
